### ISSUE TITLE
Unable to save dice presets on Mac

### ISSUE THREAD

**Issue by kwycstix** [MadScienceZone/gma-mapper#16]
Attempts to save dice presets on MAC (Big Sur, 11.6) results in:
2021-10-17 12:30:27.502 Wish[32696:2954073] WARNING: <NSSavePanel: 0x7fddc8934540> running implicitly; please run panels using NSSavePanel rather than NSApplication.
Named file is never saved.

**Comment by kwycstix** [comment]
Nothing was logged into logs or debug.log

**Comment by kwycstix** [comment]
Should the app be checking for the correct tools when starting up?  I have not installed the brew version of tcl/tk yet on my new system.  So far everything works except the file management using the built in version.

**Comment by MadScienceZone** [comment]
I'll admit the instructions in the manual need a little improvement and may not be completely clear about setting up tcl/tk (and is only one of the reasons I intend to move the mapper away from tcl/tk entirely), but you also need to be sure you have tklib installed, which you may need to get directly from the link listed in the manual; homebrew might not get it for you.

**Comment by MadScienceZone** [comment]
In response to this issue I'm also opening [issue 17](https://github.com/MadScienceZone/gma-mapper/issues/17) to create a comprehensive installer so this manual setup isn't so necessary in the future.
